data:
  dblp: ./dblp.v9/dblp.txt
  paper:
    map: ./paper/map.json
    node: ./paper/node.csv
    edge: ./paper/edge.csv
  author:
    node: ./author/node.csv
    edge: ./author/edge.csv
  venue:
    map: ./venue/map.json
  community:
    louvain: ./community/louvain.csv
    girvan_newman:
    label_propagation:
  centrality:

lib:
  max: d3.v7.js     # Used for development and debugging
  min: d3.v7.min.js # Smaller, optimized for production

# Visualization
html:
  index: index.html
