data:
  dblp: ./dblp.v9/dblp.txt
  paper:
    map: ./paper/map.json
    node: ./paper/node.csv
    edge: ./paper/edge.csv
  author:
    node: ./author/node.csv
    edge: ./author/edge.csv
  venue:
    map: ./venue/map.json
  citation: ./author/citation.json

community:
  author: results/author
  paper: results/paper

centrality:
  results: results