data:
  dblp: ./data/dblp.v9/dblp.txt
  paper: 
    node: ./data/paper/node.csv
    edge: ./data/paper/edge.csv
  author:
    node: ./data/author/node.csv
    edge: ./data/author/edge.csv
  community:
    louvain: ./data/community/louvain.csv
    girvan_newman:
    label_propagation:

test:
  dblp: ./test/dblp.v9/dblp.txt
  paper: 
    node: ./test/paper/node.csv
    edge: ./test/paper/edge.csv
  author:
    node: ./test/author/node.csv
    edge: ./test/author/edge.csv
  community:
    louvain: ./test/community/louvain.csv
    girvan_newman:
    label_propagation:

html:
  index: index.html